name: Run Prisma Migrations

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: false
        default: production

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm@9

      - name: Install backend deps
        working-directory: backend
        run: pnpm install --frozen-lockfile=false

      - name: Prisma migrate deploy
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
        run: npx --yes prisma migrate deploy --schema=prisma/schema.prisma
